<?php

use Illuminate\Database\Seeder;

class ProductTransactionsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        DB::table('product_transactions')->truncate();
        DB::table('product_transactions')->insert([
            [
              'product_id' => 4,
              'transaction_id' => 1,
              'vertical' => null,
              'horizontal' => null,
              'unit' => '反',
              'unit_price' => 36700,
              'num' => 1,
              'cut_set_num' => null,
              'cut' => 0,
              'turf_cuts' => null,
              'other_product_price' => null,
              'other_product_name' => null,
            ],
            [
              'product_id' => 3,
              'transaction_id' => 1,
              'vertical' => null,
              'horizontal' => null,
              'unit' => '反',
              'unit_price' => 36700,
              'num' => 2,
              'cut_set_num' => null,
              'cut' => 0,
              'turf_cuts' => null,
              'other_product_price' => null,
              'other_product_name' => null,
            ],
            [
              'product_id' => 1,
              'transaction_id' => 1,
              'vertical' => 10.00,
              'horizontal' => 1.00,
              'unit' => '㎡',
              'unit_price' => 46400,
              'num' => 10,
              'cut_set_num' => null,
              'cut' => 1,
              'turf_cuts' => null,
              'other_product_price' => null,
              'other_product_name' => null,
            ],
            [
              'product_id' => 1,
              'transaction_id' => 1,
              'vertical' => 8.00,
              'horizontal' => 2.00,
              'unit' => '㎡',
              'unit_price' => 2320,
              'num' => 16,
              'cut_set_num' => null,
              'cut' => 1,
              'turf_cuts' => '{
                "0": {
                  "product_id": "51",
                  "num": "8",
                  "unit_price": "1500"
                },
                "1": {
                  "product_id": "52",
                  "num": "4",
                  "unit_price": "1000"
                }
              }',
              'other_product_price' => null,
              'other_product_name' => null,
            ],
            [
              'product_id' => 14,
              'transaction_id' => 1,
              'vertical' => null,
              'horizontal' => null,
              'unit' => '本',
              'unit_price' => 2320,
              'num' => 50,
              'cut_set_num' => null,
              'cut' => 1,
              'turf_cuts' => null,
              'other_product_price' => null,
              'other_product_name' => null,
            ],
            [
              'product_id' => 36,
              'transaction_id' => 1,
              'vertical' => null,
              'horizontal' => null,
              'unit' => '1000部/セット',
              'unit_price' => 2320,
              'num' => 1,
              'cut_set_num' => null,
              'cut' => 0,
              'turf_cuts' => null,
              'other_product_price' => null,
              'other_product_name' => null,
            ],
            [
              'product_id' => 19,
              'transaction_id' => 1,
              'vertical' => null,
              'horizontal' => null,
              'unit' => '本',
              'unit_price' => 200,
              'num' => 4,
              'cut_set_num' => null,
              'cut' => 0,
              'turf_cuts' => null,
              'other_product_price' => null,
              'other_product_name' => null,
            ],
            [
              'product_id' => null,
              'transaction_id' => 1,
              'vertical' => null,
              'horizontal' => null,
              'unit' => '反',
              'unit_price' => 23200,
              'num' => 5,
              'cut_set_num' => null,
              'cut' => 0,
              'turf_cuts' => null,
              'other_product_price' => 40000,
              'other_product_name' => '芝丈30ｍｍ　白　　１m×10ｍ',
            ],
            [
              'product_id' => 4,
              'transaction_id' => 2,
              'vertical' => null,
              'horizontal' => null,
              'unit' => '反',
              'unit_price' => 23200,
              'num' => 1,
              'cut_set_num' => null,
              'cut' => 0,
              'turf_cuts' => null,
              'other_product_price' => null,
              'other_product_name' => null,
            ],
            [
              'product_id' => 3,
              'transaction_id' => 2,
              'vertical' => null,
              'horizontal' => null,
              'unit' => '反',
              'unit_price' => 23200,
              'num' => 2,
              'cut_set_num' => null,
              'cut' => 0,
              'turf_cuts' => null,
              'other_product_price' => null,
              'other_product_name' => null,
            ],
            [
              'product_id' => 1,
              'transaction_id' => 2,
              'vertical' => 10.00,
              'horizontal' => 1.00,
              'unit' => '㎡',
              'unit_price' => 23200,
              'num' => 10,
              'cut_set_num' => null,
              'cut' => 1,
              'turf_cuts' => null,
              'other_product_price' => null,
              'other_product_name' => null,
            ],
            [
              'product_id' => 1,
              'transaction_id' => 6,
              'vertical' => null,
              'horizontal' => null,
              'unit' => '反',
              'unit_price' => 23200,
              'num' => 10,
              'cut_set_num' => null,
              'cut' => 0,
              'turf_cuts' => null,
              'other_product_price' => null,
              'other_product_name' => null,
            ],
            [
              'product_id' => 1,
              'transaction_id' => 7,
              'vertical' => null,
              'horizontal' => null,
              'unit' => '反',
              'unit_price' => 23200,
              'num' => 20,
              'cut_set_num' => null,
              'cut' => 0,
              'turf_cuts' => null,
              'other_product_price' => null,
              'other_product_name' => null,
            ],
            [
              'product_id' => 1,
              'transaction_id' => 5,
              'vertical' => null,
              'horizontal' => null,
              'unit' => '反',
              'unit_price' => 23200,
              'num' => 5,
              'cut_set_num' => null,
              'cut' => 0,
              'turf_cuts' => null,
              'other_product_price' => null,
              'other_product_name' => null,
            ],
            [
              'product_id' => 2,
              'transaction_id' => 5,
              'vertical' => null,
              'horizontal' => null,
              'unit' => '反',
              'unit_price' => 23200,
              'num' => 5,
              'cut_set_num' => null,
              'cut' => 0,
              'turf_cuts' => null,
              'other_product_price' => null,
              'other_product_name' => null,
            ],
            [
              'product_id' => null,
              'transaction_id' => 8,
              'vertical' => null,
              'horizontal' => null,
              'unit' => '反',
              'unit_price' => 23200,
              'num' => 5,
              'cut_set_num' => null,
              'cut' => 0,
              'turf_cuts' => null,
              'other_product_price' => 40000,
              'other_product_name' => '芝丈30ｍｍ　白　　１m×10ｍ',
            ],
            [
              'product_id' => 3,
              'transaction_id' => 14,
              'vertical' => null,
              'horizontal' => null,
              'unit' => '反',
              'unit_price' => 23200,
              'num' => 20,
              'cut_set_num' => null,
              'cut' => 0,
              'turf_cuts' => null,
              'other_product_price' => null,
              'other_product_name' => null,
            ],
            [
              'product_id' => 67,
              'transaction_id' => 35,
              'vertical' => null,
              'horizontal' => null,
              'unit' => '反',
              'unit_price' => 23200,
              'num' => 10,
              'cut_set_num' => null,
              'cut' => 0,
              'turf_cuts' => null,
              'other_product_price' => null,
              'other_product_name' => null,
            ],
            [
              'product_id' => 1,
              'transaction_id' => 41,
              'vertical' => null,
              'horizontal' => null,
              'unit' => '反',
              'unit_price' => 23200,
              'num' => 12,
              'cut_set_num' => null,
              'cut' => 0,
              'turf_cuts' => null,
              'other_product_price' => null,
              'other_product_name' => null,
            ],
            [
              'product_id' => 14,
              'transaction_id' => 41,
              'vertical' => null,
              'horizontal' => null,
              'unit' => '箱',
              'unit_price' => 23200,
              'num' => 1,
              'cut_set_num' => null,
              'cut' => 0,
              'turf_cuts' => null,
              'other_product_price' => null,
              'other_product_name' => null,
            ],
            [
              'product_id' => 1,
              'transaction_id' => 44,
              'vertical' => null,
              'horizontal' => null,
              'unit' => '反',
              'unit_price' => 23200,
              'num' => 1,
              'cut_set_num' => null,
              'cut' => 0,
              'turf_cuts' => null,
              'other_product_price' => null,
              'other_product_name' => null,
            ],
            [
              'product_id' => 1,
              'transaction_id' => 46,
              'vertical' => null,
              'horizontal' => null,
              'unit' => '反',
              'unit_price' => 23200,
              'num' => 1,
              'cut_set_num' => null,
              'cut' => 0,
              'turf_cuts' => null,
              'other_product_price' => null,
              'other_product_name' => null,
            ],
            [
              'product_id' => 1,
              'transaction_id' => 47,
              'vertical' => null,
              'horizontal' => null,
              'unit' => '反',
              'unit_price' => 23200,
              'num' => 1,
              'cut_set_num' => null,
              'cut' => 0,
              'turf_cuts' => null,
              'other_product_price' => null,
              'other_product_name' => null,
            ],
            [
              'product_id' => 1,
              'transaction_id' => 48,
              'vertical' => null,
              'horizontal' => null,
              'unit' => '反',
              'unit_price' => 23200,
              'num' => 1,
              'cut_set_num' => null,
              'cut' => 0,
              'turf_cuts' => null,
              'other_product_price' => null,
              'other_product_name' => null,
            ],
            [
              'product_id' => 1,
              'transaction_id' => 49,
              'vertical' => null,
              'horizontal' => null,
              'unit' => '反',
              'unit_price' => 23200,
              'num' => 1,
              'cut_set_num' => null,
              'cut' => 0,
              'turf_cuts' => null,
              'other_product_price' => null,
              'other_product_name' => null,
            ],
            // PDFテスト用
            [
              'product_id' => 1,
              'transaction_id' => 50,
              'vertical' => 8.00,
              'horizontal' => 2.00,
              'unit' => '㎡',
              'unit_price' => 2320,
              'num' => 16,
              'cut_set_num' => 2,
              'cut' => 1,
              'turf_cuts' => '{
                "0": {
                  "product_id": "51",
                  "num": "8",
                  "unit_price": "1500"
                },
                "1": {
                  "product_id": "56",
                  "num": "4",
                  "unit_price": "1000"
                }
              }',
              'other_product_price' => null,
              'other_product_name' => null,
            ],
            [
              'product_id' => 3,
              'transaction_id' => 50,
              'vertical' => null,
              'horizontal' => null,
              'unit' => '反',
              'unit_price' => 23200,
              'num' => 2,
              'cut_set_num' => null,
              'cut' => 0,
              'turf_cuts' => '{
                "0": {
                  "product_id": "53",
                  "num": "2",
                  "unit_price": "15000"
                }
              }',
              'turf_cuts' => null,
              'other_product_price' => null,
              'other_product_name' => null,
            ],
            [
              'product_id' => 14,
              'transaction_id' => 50,
              'vertical' => null,
              'horizontal' => null,
              'unit' => '本',
              'unit_price' => 30,
              'num' => 50,
              'cut_set_num' => null,
              'cut' => 1,
              'turf_cuts' => null,
              'other_product_price' => null,
              'other_product_name' => null,
            ],
            [
              'product_id' => 36,
              'transaction_id' => 50,
              'vertical' => null,
              'horizontal' => null,
              'unit' => '1000部/セット',
              'unit_price' => 5000,
              'num' => 1,
              'cut_set_num' => null,
              'cut' => 0,
              'turf_cuts' => null,
              'other_product_price' => null,
              'other_product_name' => null,
            ],
            [
              'product_id' => 19,
              'transaction_id' => 50,
              'vertical' => null,
              'horizontal' => null,
              'unit' => '本',
              'unit_price' => 50,
              'num' => 4,
              'cut_set_num' => null,
              'cut' => 0,
              'turf_cuts' => null,
              'other_product_price' => null,
              'other_product_name' => null,
            ],
            [
              'product_id' => null,
              'transaction_id' => 50,
              'vertical' => null,
              'horizontal' => null,
              'unit' => '反',
              'unit_price' => 40000,
              'num' => 5,
              'cut_set_num' => null,
              'cut' => 0,
              'turf_cuts' => null,
              'other_product_price' => 40000,
              'other_product_name' => '芝丈30ｍｍ　白　　１m×10ｍ',
            ],
        ]);
    }
}
