<?php

use Illuminate\Database\Seeder;

class ProductQuotationsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        DB::table('product_quotations')->truncate();
        DB::table('product_quotations')->insert([
          // 見積もり番号1の内訳
            [
                'quotation_id' => 1,
                'product_id' => 1,
                'num' => 25,
                'unit' => '㎡',
                'other_product' => 0,
                'name' => null,
                'unit_price' => null,
                'price' => null,
                'memo' => 'ぜんかくにじゅうごもじぜんかくにじゅうごもじぜんか',
            ],
            [
                'quotation_id' => 1,
                'product_id' => 1,
                'num' => 15,
                'unit' => '㎡',
                'other_product' => 0,
                'name' => null,
                'unit_price' => null,
                'price' => null,
                'memo' => 'ぜんかくにじゅうごもじぜんかくにじゅうごもじぜんか',
            ],
            [
                'quotation_id' => 1,
                'product_id' => null,
                'num' => 2,
                'unit' => '円',
                'other_product' => 1,
                'name' => '出張費',
                'unit_price' => 1500,
                'price' => 1500,
                'memo' => 'ぜんかくにじゅうごもじぜんかくにじゅうごもじぜんか',
            ],
          // 見積もり番号2の内訳
            [
                'quotation_id' => 2,
                'product_id' => 2,
                'num' => 12,
                'unit' => '㎡',
                'other_product' => 0,
                'name' => null,
                'unit_price' => null,
                'price' => null,
                'memo' => 'ぜんかくにじゅうごもじぜんかくにじゅうごもじぜんか',
            ],
            [
                'quotation_id' => 2,
                'product_id' => 4,
                'num' => 5,
                'unit' => '㎡',
                'other_product' => 0,
                'name' => null,
                'unit_price' => null,
                'price' => null,
                'memo' => 'ぜんかくにじゅうごもじぜんかくにじゅうごもじぜんか',
            ],
            [
                'quotation_id' => 2,
                'product_id' => null,
                'num' => 1,
                'unit' => '円',
                'other_product' => 1,
                'name' => '下地改良',
                'unit_price' => 20000,
                'price' => 20000,
                'memo' => 'ぜんかくにじゅうごもじぜんかくにじゅうごもじぜんか',
            ],
            [
                'quotation_id' => 2,
                'product_id' => null,
                'num' => 2,
                'unit' => '円',
                'other_product' => 1,
                'name' => '出張費',
                'unit_price' => 1500,
                'price' => 1500,
                'memo' => 'ぜんかくにじゅうごもじぜんかくにじゅうごもじぜんか',
            ],
          // 見積もり番号3の内訳
            [
                'quotation_id' => 3,
                'product_id' => 5,
                'num' => 77,
                'unit' => '㎡',
                'other_product' => 0,
                'name' => null,
                'unit_price' => null,
                'price' => null,
                'memo' => 'ぜんかくにじゅうごもじぜんかくにじゅうごもじぜんか',
            ],
            [
                'quotation_id' => 3,
                'product_id' => 3,
                'num' => 30,
                'unit' => '㎡',
                'other_product' => 0,
                'name' => null,
                'unit_price' => null,
                'price' => null,
                'memo' => 'ぜんかくにじゅうごもじぜんかくにじゅうごもじぜんか',
            ],
            [
                'quotation_id' => 3,
                'product_id' => null,
                'num' => 1,
                'unit' => '円',
                'other_product' => 1,
                'name' => '下地改良',
                'unit_price' => 50000,
                'price' => 50000,
                'memo' => 'ぜんかくにじゅうごもじぜんかくにじゅうごもじぜんか',
            ],
            [
                'quotation_id' => 3,
                'product_id' => null,
                'num' => 2,
                'unit' => '円',
                'other_product' => 1,
                'name' => '出張費',
                'unit_price' => 10000,
                'price' => 10000,
                'memo' => 'ぜんかくにじゅうごもじぜんかくにじゅうごもじぜんか',
            ],
          // 見積もり番号4の内訳
            [
                'quotation_id' => 4,
                'product_id' => 7,
                'num' => 77,
                'unit' => '㎡',
                'other_product' => 0,
                'name' => null,
                'unit_price' => null,
                'price' => null,
                'memo' => 'ぜんかくにじゅうごもじぜんかくにじゅうごもじぜんか',
            ],
            [
                'quotation_id' => 4,
                'product_id' => 8,
                'num' => 30,
                'unit' => '㎡',
                'other_product' => 0,
                'name' => null,
                'unit_price' => null,
                'price' => null,
                'memo' => 'ぜんかくにじゅうごもじぜんかくにじゅうごもじぜんか',
            ],
            [
                'quotation_id' => 4,
                'product_id' => null,
                'num' => 1,
                'unit' => '円',
                'other_product' => 1,
                'name' => '下地改良',
                'unit_price' => 100000,
                'price' => 100000,
                'memo' => 'ぜんかくにじゅうごもじぜんかくにじゅうごもじぜんか',
            ],
            [
                'quotation_id' => 4,
                'product_id' => null,
                'num' => 2,
                'unit' => '円',
                'other_product' => 1,
                'name' => '出張費',
                'unit_price' => 5000,
                'price' => 5000,
                'memo' => 'ぜんかくにじゅうごもじぜんかくにじゅうごもじぜんか',
            ],
          // 見積もり番号5の内訳
            [
                'quotation_id' => 5,
                'product_id' => 2,
                'num' => 77,
                'unit' => '㎡',
                'other_product' => 0,
                'name' => null,
                'unit_price' => null,
                'price' => null,
                'memo' => 'ぜんかくにじゅうごもじぜんかくにじゅうごもじぜんか',
            ],
            [
                'quotation_id' => 5,
                'product_id' => 8,
                'num' => 30,
                'unit' => '㎡',
                'other_product' => 0,
                'name' => null,
                'unit_price' => null,
                'price' => null,
                'memo' => 'ぜんかくにじゅうごもじぜんかくにじゅうごもじぜんか',
            ],
            [
                'quotation_id' => 5,
                'product_id' => null,
                'num' => 1,
                'unit' => '円',
                'other_product' => 1,
                'name' => '下地改良',
                'unit_price' => 120000,
                'price' => 120000,
                'memo' => 'ぜんかくにじゅうごもじぜんかくにじゅうごもじぜんか',
            ],
            [
                'quotation_id' => 5,
                'product_id' => null,
                'num' => 2,
                'unit' => '円',
                'other_product' => 1,
                'name' => '出張費',
                'unit_price' => 5000,
                'price' => 5000,
                'memo' => 'ぜんかくにじゅうごもじぜんかくにじゅうごもじぜんか',
            ],
          // 見積もり番号5の内訳
            [
                'quotation_id' => 6,
                'product_id' => 2,
                'num' => 77,
                'unit' => '㎡',
                'other_product' => 0,
                'name' => null,
                'unit_price' => null,
                'price' => null,
                'memo' => 'ぜんかくにじゅうごもじぜんかくにじゅうごもじぜんか',
            ],
            [
                'quotation_id' => 5,
                'product_id' => 8,
                'num' => 30,
                'unit' => '㎡',
                'other_product' => 0,
                'name' => null,
                'unit_price' => null,
                'price' => null,
                'memo' => 'ぜんかくにじゅうごもじぜんかくにじゅうごもじぜんか',
            ],
            [
                'quotation_id' => 5,
                'product_id' => null,
                'num' => 1,
                'unit' => '円',
                'other_product' => 1,
                'name' => '下地改良',
                'unit_price' => 120000,
                'price' => 120000,
                'memo' => 'ぜんかくにじゅうごもじぜんかくにじゅうごもじぜんか',
            ],
            [
                'quotation_id' => 5,
                'product_id' => null,
                'num' => 2,
                'unit' => '円',
                'other_product' => 1,
                'name' => '出張費',
                'unit_price' => null,
                'price' => 5000,
                'memo' => 'ぜんかくにじゅうごもじぜんかくにじゅうごもじぜんか',
            ],
            // 見積もり番号7の内訳
            [
                'quotation_id' => 7,
                'product_id' => 2,
                'num' => 77,
                'unit' => '㎡',
                'other_product' => 0,
                'name' => null,
                'unit_price' => null,
                'price' => null,
                'memo' => 'ぜんかくにじゅうごもじぜんかくにじゅうごもじぜんか',
            ],
            [
                'quotation_id' => 7,
                'product_id' => null,
                'num' => 1,
                'unit' => '円',
                'other_product' => 1,
                'name' => '下地改良',
                'unit_price' => 120000,
                'price' => 120000,
                'memo' => 'ぜんかくにじゅうごもじぜんかくにじゅうごもじぜんか',
            ],
            // 見積もり番号8の内訳
            [
                'quotation_id' => 8,
                'product_id' => 7,
                'num' => 30,
                'unit' => '㎡',
                'other_product' => 0,
                'name' => null,
                'unit_price' => 6000,
                'price' => 180000,
                'memo' => 'ぜんかくにじゅうごもじぜんかくにじゅうごもじぜんか',
            ],
            [
                'quotation_id' => 8,
                'product_id' => null,
                'num' => 2,
                'unit' => '円',
                'other_product' => 1,
                'name' => '出張費',
                'unit_price' => 2500,
                'price' => 5000,
                'memo' => 'ぜんかくにじゅうごもじぜんかくにじゅうごもじぜんか',
            ],
            // 見積書コピー見積もり番号10の内訳
            [
                'quotation_id' => 10,
                'product_id' => 7,
                'num' => 30,
                'unit' => '㎡',
                'other_product' => 0,
                'name' => null,
                'unit_price' => 6000,
                'price' => 180000,
                'memo' => 'ぜんかくにじゅうごもじぜんかくにじゅうごもじぜんか',
            ],
            [
                'quotation_id' => 10,
                'product_id' => null,
                'num' => 1,
                'unit' => 'かえる',
                'other_product' => 1,
                'name' => 'カエルコピー費用',
                'unit_price' => 5000,
                'price' => 5000,
                'memo' => 'ぜんかくにじゅうごもじぜんかくにじゅうごもじぜんか',
            ],
            [
                'quotation_id' => 15,
                'product_id' => 79,
                'num' => 51,
                'unit' => 'm',
                'other_product' =>0,
                'name' => 'エスキューブ工法',
                'unit_price' => 170,
                'price' => 8670,
                'memo' => 'ぜんかくにじゅうごもじぜんかくにじゅうごもじぜんか',
            ],
          // 見積もり番号19の内訳
            [
                'quotation_id' => 19,
                'product_id' => 1,
                'num' => 77,
                'unit' => '㎡',
                'other_product' => 0,
                'name' => null,
                'unit_price' => null,
                'price' => null,
                'memo' => 'ぜんかくにじゅうごもじぜんかくにじゅうごもじぜんか',
            ],
            [
                'quotation_id' => 19,
                'product_id' => 2,
                'num' => 77,
                'unit' => '㎡',
                'other_product' => 0,
                'name' => null,
                'unit_price' => null,
                'price' => null,
                'memo' => 'ぜんかくにじゅうごもじぜんかくにじゅうごもじぜんか',
            ],
            [
                'quotation_id' => 19,
                'product_id' => 3,
                'num' => 77,
                'unit' => '㎡',
                'other_product' => 0,
                'name' => null,
                'unit_price' => null,
                'price' => null,
                'memo' => 'ぜんかくにじゅうごもじぜんかくにじゅうごもじぜんか',
            ],
            [
                'quotation_id' => 19,
                'product_id' => 4,
                'num' => 77,
                'unit' => '㎡',
                'other_product' => 0,
                'name' => null,
                'unit_price' => null,
                'price' => null,
                'memo' => 'ぜんかくにじゅうごもじぜんかくにじゅうごもじぜんか',
            ],
            [
                'quotation_id' => 19,
                'product_id' => 5,
                'num' => 77,
                'unit' => '㎡',
                'other_product' => 0,
                'name' => null,
                'unit_price' => null,
                'price' => null,
                'memo' => 'ぜんかくにじゅうごもじぜんかくにじゅうごもじぜんか',
            ],
            [
                'quotation_id' => 19,
                'product_id' => 6,
                'num' => 77,
                'unit' => '㎡',
                'other_product' => 0,
                'name' => null,
                'unit_price' => null,
                'price' => null,
                'memo' => 'ぜんかくにじゅうごもじぜんかくにじゅうごもじぜんか',
            ],
            [
                'quotation_id' => 19,
                'product_id' => 7,
                'num' => 77,
                'unit' => '㎡',
                'other_product' => 0,
                'name' => null,
                'unit_price' => null,
                'price' => null,
                'memo' => 'ぜんかくにじゅうごもじぜんかくにじゅうごもじぜんか',
            ],
            [
                'quotation_id' => 19,
                'product_id' => 8,
                'num' => 30,
                'unit' => '㎡',
                'other_product' => 0,
                'name' => null,
                'unit_price' => null,
                'price' => null,
                'memo' => 'ぜんかくにじゅうごもじぜんかくにじゅうごもじぜんか',
            ],
            [
                'quotation_id' => 19,
                'product_id' => 18,
                'num' => 30,
                'unit' => 'm',
                'other_product' => 0,
                'name' => null,
                'unit_price' => null,
                'price' => null,
                'memo' => 'ぜんかくにじゅうごもじぜんかくにじゅうごもじぜんか',
            ],
            [
                'quotation_id' => 19,
                'product_id' => 19,
                'num' => 30,
                'unit' => 'm',
                'other_product' => 0,
                'name' => null,
                'unit_price' => null,
                'price' => null,
                'memo' => 'ぜんかくにじゅうごもじぜんかくにじゅうごもじぜんか',
            ],
            [
                'quotation_id' => 19,
                'product_id' => 20,
                'num' => 30,
                'unit' => 'm',
                'other_product' => 0,
                'name' => null,
                'unit_price' => null,
                'price' => null,
                'memo' => 'ぜんかくにじゅうごもじぜんかくにじゅうごもじぜんか',
            ],
            [
                'quotation_id' => 19,
                'product_id' => null,
                'num' => 1,
                'unit' => '円',
                'other_product' => 1,
                'name' => '下地改良',
                'unit_price' => 100000,
                'price' => 100000,
                'memo' => 'ぜんかくにじゅうごもじぜんかくにじゅうごもじぜんか',
            ],
            [
                'quotation_id' => 19,
                'product_id' => null,
                'num' => 2,
                'unit' => '円',
                'other_product' => 1,
                'name' => '出張費',
                'unit_price' => 5000,
                'price' => 5000,
                'memo' => 'ぜんかくにじゅうごもじぜんかくにじゅうごもじぜんか',
            ],
            [
                'quotation_id' => 19,
                'product_id' => null,
                'num' => 1,
                'unit' => '円',
                'other_product' => 1,
                'name' => '廃材片付け費',
                'unit_price' => 5000,
                'price' => 5000,
                'memo' => 'ぜんかくにじゅうごもじぜんかくにじゅうごもじぜんか',
            ],
            [
                'quotation_id' => 20,
                'product_id' => 1,
                'num' => 55,
                'unit' => '㎡',
                'other_product' => 0,
                'name' => null,
                'unit_price' => null,
                'price' => null,
                'memo' => 'ぜんかくにじゅうごもじぜんかくにじゅうごもじぜんか',
            ],
            [
                'quotation_id' => 20,
                'product_id' => 1,
                'num' => 45,
                'unit' => '㎡',
                'other_product' => 0,
                'name' => null,
                'unit_price' => null,
                'price' => null,
                'memo' => 'ぜんかくにじゅうごもじぜんかくにじゅうごもじぜんか',
            ],
        ]);
    }
}
