<?php

use Illuminate\Database\Seeder;

class ProductQuotationMaterialsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        DB::table('product_quotation_materials')->truncate();
        DB::table('product_quotation_materials')->insert([
            [
              'product_id' => 4,
              'quotation_id' => 14,
              'vertical' => null,
              'horizontal' => null,
              'unit' => '反',
              'unit_price' => 50000,
              'num' => 1,
              'cut' => 0,
              'turf_cuts' => '[]',
              // 'other_product_price' => null,
              'other_product_name' => null,
                'memo' => 'ぜんかくにじゅうごもじぜんかくにじゅうごもじぜんか',
              'status' => 1,
            ],
            [
              'product_id' => 3,
              'quotation_id' => 14,
              'vertical' => null,
              'horizontal' => null,
              'unit' => '反',
              'unit_price' => 50000,
              'num' => 2,
              'cut' => 0,
              'turf_cuts' => '[]',
              // 'other_product_price' => null,
              'other_product_name' => null,
                'memo' => 'ぜんかくにじゅうごもじぜんかくにじゅうごもじぜんか',
              'status' => 1,
            ],
            [
              'product_id' => 7,
              'quotation_id' => 14,
              'vertical' => 7.20,
              'horizontal' => 1.22,
              'unit' => '㎡',
              'unit_price' => 1810,
              'num' => 8.8,
              'cut' => 1,
              'turf_cuts' => '[{"product_id": "71","num": "7","unit": "m","unit_price": "1500"}]',
              // 'other_product_price' => null,
              'other_product_name' => null,
                'memo' => 'ぜんかくにじゅうごもじぜんかくにじゅうごもじぜんか',
              'status' => 1,
            ],
            [
              'product_id' => 7,
              'quotation_id' => 14,
              'vertical' => 8.00,
              'horizontal' => 1.50,
              'unit' => '㎡',
              'unit_price' => 1810,
              'num' => 12,
              'cut' => 1,
              'turf_cuts' => '[{"product_id": "71","num": "8","unit": "m","unit_price": "1500"},{"product_id": "71","num": "8","unit": "m","unit_price": "1000"}]',
              // 'other_product_price' => null,
              'other_product_name' => null,
                'memo' => 'ぜんかくにじゅうごもじぜんかくにじゅうごもじぜんか',
              'status' => 1,
            ],
            [
              'product_id' => 14,
              'quotation_id' => 14,
              'vertical' => null,
              'horizontal' => null,
              'unit' => '本',
              'unit_price' => 30,
              'num' => 50,
              'cut' => 0,
              'turf_cuts' => '[]',
              // 'other_product_price' => null,
              'other_product_name' => null,
              'memo' => 'ぜんかくにじゅうごもじぜんかくにじゅうごもじぜんか',
              'status' => 1,
            ],
            [
              'product_id' => 18,
              'quotation_id' => 14,
              'vertical' => null,
              'horizontal' => null,
              'unit' => 'm2',
              'unit_price' => 480,
              'num' => 18,
              'cut' => 0,
              'turf_cuts' => '[]',
              // 'other_product_price' => null,
              'other_product_name' => null,
              'memo' => 'ぜんかくにじゅうごもじぜんかくにじゅうごもじぜんか',
              'status' => 1,
            ],
            [
              'product_id' => null,
              'quotation_id' => 14,
              'vertical' => null,
              'horizontal' => null,
              'unit' => '1式',
              'unit_price' => 3000,
              'num' => 1,
              'cut' => 0,
              'turf_cuts' => '[]',
              // 'other_product_price' => null,
              'other_product_name' => '送料',
              'memo' => 'ぜんかくにじゅうごもじぜんかくにじゅうごもじぜんか',
              'status' => 1,
            ],
            [
              'product_id' => 2,
              'quotation_id' => 18,
              'vertical' => null,
              'horizontal' => null,
              'unit' => '反',
              'unit_price' => 98200,
              'num' => 1,
              'cut' => 0,
              'turf_cuts' => '[]',
              // 'other_product_price' => null,
              'other_product_name' => null,
              'memo' => 'ぜんかくにじゅうごもじぜんかくにじゅうごもじぜんか',
              'status' => 1,
            ],
            [
              'product_id' => 3,
              'quotation_id' => 18,
              'vertical' => null,
              'horizontal' => null,
              'unit' => '反',
              'unit_price' => 36700,
              'num' => 1,
              'cut' => 0,
              'turf_cuts' => '[]',
              // 'other_product_price' => null,
              'other_product_name' => null,
              'memo' => 'ぜんかくにじゅうごもじぜんかくにじゅうごもじぜんか',
              'status' => 1,
            ],
            [
              'product_id' => 67,
              'quotation_id' => 18,
              'vertical' => null,
              'horizontal' => null,
              'unit' => '反',
              'unit_price' => 36700,
              'num' => 1,
              'cut' => 0,
              'turf_cuts' => '[]',
              // 'other_product_price' => null,
              'other_product_name' => null,
              'memo' => 'ぜんかくにじゅうごもじぜんかくにじゅうごもじぜんか',
              'status' => 1,
            ],
            [
              'product_id' => 5,
              'quotation_id' => 18,
              'vertical' => null,
              'horizontal' => null,
              'unit' => '反',
              'unit_price' => 127800,
              'num' => 1,
              'cut' => 0,
              'turf_cuts' => '[]',
              // 'other_product_price' => null,
              'other_product_name' => null,
              'memo' => 'ぜんかくにじゅうごもじぜんかくにじゅうごもじぜんか',
              'status' => 1,
            ],
            [
              'product_id' => 6,
              'quotation_id' => 18,
              'vertical' => null,
              'horizontal' => null,
              'unit' => '反',
              'unit_price' => 127800,
              'num' => 1,
              'cut' => 0,
              'turf_cuts' => '[]',
              // 'other_product_price' => null,
              'other_product_name' => null,
              'memo' => 'ぜんかくにじゅうごもじぜんかくにじゅうごもじぜんか',
              'status' => 1,
            ],
            [
              'product_id' => 3,
              'quotation_id' => 18,
              'vertical' => null,
              'horizontal' => null,
              'unit' => '反',
              'unit_price' => 50000,
              'num' => 2,
              'cut' => 0,
              'turf_cuts' => '[]',
              // 'other_product_price' => null,
              'other_product_name' => null,
              'memo' => 'ぜんかくにじゅうごもじぜんかくにじゅうごもじぜんか',
              'status' => 1,
            ],
            [
              'product_id' => 7,
              'quotation_id' => 18,
              'vertical' => 7.50,
              'horizontal' => 1.30,
              'unit' => '㎡',
              'unit_price' => 1810,
              'num' => 9.7,
              'cut' => 1,
              'turf_cuts' => '[{"product_id":"71","num":"3","unit":"m","unit_price":"1500"}]',
              // 'other_product_price' => null,
              'other_product_name' => null,
              'memo' => 'ぜんかくにじゅうごもじぜんかくにじゅうごもじぜんか',
              'status' => 1,
            ],
            [
              'product_id' => 14,
              'quotation_id' => 18,
              'vertical' => null,
              'horizontal' => null,
              'unit' => '本',
              'unit_price' => 30,
              'num' => 50,
              'cut' => 0,
              'turf_cuts' => '[]',
              // 'other_product_price' => null,
              'other_product_name' => null,
              'memo' => 'ぜんかくにじゅうごもじぜんかくにじゅうごもじぜんか',
              'status' => 1,
            ],
            [
              'product_id' => 15,
              'quotation_id' => 18,
              'vertical' => null,
              'horizontal' => null,
              'unit' => '本',
              'unit_price' => 30,
              'num' => 50,
              'cut' => 0,
              'turf_cuts' => '[]',
              // 'other_product_price' => null,
              'other_product_name' => null,
              'memo' => 'ぜんかくにじゅうごもじぜんかくにじゅうごもじぜんか',
              'status' => 1,
            ],
            [
              'product_id' => 16,
              'quotation_id' => 18,
              'vertical' => null,
              'horizontal' => null,
              'unit' => 'm',
              'unit_price' => 300,
              'num' => 20,
              'cut' => 0,
              'turf_cuts' => '[]',
              // 'other_product_price' => null,
              'other_product_name' => null,
              'memo' => 'ぜんかくにじゅうごもじぜんかくにじゅうごもじぜんか',
              'status' => 1,
            ],
            [
              'product_id' => 25,
              'quotation_id' => 18,
              'vertical' => null,
              'horizontal' => null,
              'unit' => '袋',
              'unit_price' => 1800,
              'num' => 2,
              'cut' => 0,
              'turf_cuts' => '[]',
              // 'other_product_price' => null,
              'other_product_name' => null,
              'memo' => 'ぜんかくにじゅうごもじぜんかくにじゅうごもじぜんか',
              'status' => 1,
            ],
            [
              'product_id' => 18,
              'quotation_id' => 18,
              'vertical' => null,
              'horizontal' => null,
              'unit' => 'm2',
              'unit_price' => 480,
              'num' => 1,
              'cut' => 0,
              'turf_cuts' => '[]',
              // 'other_product_price' => null,
              'other_product_name' => null,
              'memo' => 'ぜんかくにじゅうごもじぜんかくにじゅうごもじぜんか',
              'status' => 1,
            ],
            [
              'product_id' => 31,
              'quotation_id' => 18,
              'vertical' => null,
              'horizontal' => null,
              'unit' => 'セット',
              'unit_price' => 2500,
              'num' => 1,
              'cut' => 0,
              'turf_cuts' => '[]',
              // 'other_product_price' => null,
              'other_product_name' => null,
              'memo' => 'ぜんかくにじゅうごもじぜんかくにじゅうごもじぜんか',
              'status' => 1,
            ],
            [
              'product_id' => 32,
              'quotation_id' => 18,
              'vertical' => null,
              'horizontal' => null,
              'unit' => 'セット',
              'unit_price' => 2500,
              'num' => 1,
              'cut' => 0,
              'turf_cuts' => '[]',
              // 'other_product_price' => null,
              'other_product_name' => null,
              'memo' => 'ぜんかくにじゅうごもじぜんかくにじゅうごもじぜんか',
              'status' => 1,
            ],
            [
              'product_id' => 33,
              'quotation_id' => 18,
              'vertical' => null,
              'horizontal' => null,
              'unit' => 'セット',
              'unit_price' => 2500,
              'num' => 1,
              'cut' => 0,
              'turf_cuts' => '[]',
              // 'other_product_price' => null,
              'other_product_name' => null,
              'memo' => 'ぜんかくにじゅうごもじぜんかくにじゅうごもじぜんか',
              'status' => 1,
            ],
            [
              'product_id' => 34,
              'quotation_id' => 18,
              'vertical' => null,
              'horizontal' => null,
              'unit' => 'セット',
              'unit_price' => 2500,
              'num' => 1,
              'cut' => 0,
              'turf_cuts' => '[]',
              // 'other_product_price' => null,
              'other_product_name' => null,
              'memo' => 'ぜんかくにじゅうごもじぜんかくにじゅうごもじぜんか',
              'status' => 1,
            ],
            [
              'product_id' => 35,
              'quotation_id' => 18,
              'vertical' => null,
              'horizontal' => null,
              'unit' => 'セット',
              'unit_price' => 2500,
              'num' => 1,
              'cut' => 0,
              'turf_cuts' => '[]',
              // 'other_product_price' => null,
              'other_product_name' => null,
              'memo' => 'ぜんかくにじゅうごもじぜんかくにじゅうごもじぜんか',
              'status' => 1,
            ],
            [
              'product_id' => 1,
              'quotation_id' => 21,
              'vertical' => null,
              'horizontal' => null,
              'unit' => '反',
              'unit_price' => 50000,
              'num' => 2,
              'cut' => 0,
              'turf_cuts' => '[]',
              // 'other_product_price' => null,
              'other_product_name' => null,
              'memo' => 'ぜんかくにじゅうごもじぜんかくにじゅうごもじぜんか',
              'status' => 1,
            ],
            [
              'product_id' => 1,
              'quotation_id' => 21,
              'vertical' => 2,
              'horizontal' => 7.7,
              'unit' => 'm2',
              'unit_price' => 5000,
              'num' => 15.4,
              'cut' => 1,
              'turf_cuts' => '[{"product_id": "71","num": "7","unit": "m","unit_price": "1500"}]',
              // 'other_product_price' => null,
              'other_product_name' => null,
              'memo' => 'ぜんかくにじゅうごもじぜんかくにじゅうごもじぜんか',
              'status' => 1,
            ],
            [
              'product_id' => 7,
              'quotation_id' => 21,
              'vertical' => 7.20,
              'horizontal' => 1.22,
              'unit' => '㎡',
              'unit_price' => 1810,
              'num' => 8.8,
              'cut' => 1,
              'turf_cuts' => '[{"product_id": "71","num": "7","unit": "m","unit_price": "1500"}]',
              // 'other_product_price' => null,
              'other_product_name' => null,
              'memo' => 'ぜんかくにじゅうごもじぜんかくにじゅうごもじぜんか',
              'status' => 1,
            ],
            [
              'product_id' => 3,
              'quotation_id' => 21,
              'vertical' => null,
              'horizontal' => null,
              'unit' => '反',
              'unit_price' => 50000,
              'num' => 5,
              'cut' => 0,
              'turf_cuts' => '[]',
              // 'other_product_price' => null,
              'other_product_name' => null,
              'memo' => 'ぜんかくにじゅうごもじぜんかくにじゅうごもじぜんか',
              'status' => 1,
            ],
        ]);
    }
}
