<?php

use Illuminate\Database\Seeder;

class QuotationsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        DB::table('quotations')->truncate();
        DB::table('quotations')->insert([
            [
                'id' => 1,
                'type' => 0,
                'name' => '見積もり名',
                'user_id' => 2,
                'staff_name' => '担当者',
                'contact_id' => 11,
                'sub_total' => 80000,
                'total' => 88000,
                'payee' => "",
                'memo' => '備考🐸',
            ],
            [
                'id' => 2,
                'type' => 0,
                'name' => '見積もり名',
                'user_id' => 2,
                'staff_name' => '担当者',
                'contact_id' => 48,
                'sub_total' => 30000,
                'total' => 33000,
                'payee' => "",
                'memo' => '備考🐸',
            ],
            [
                'id' => 3,
                'type' => 0,
                'name' => '見積もり名',
                'user_id' => 3,
                'staff_name' => '担当者',
                'contact_id' => 12,
                'sub_total' => 150000,
                'total' => 175000,
                'payee' => "",
                'memo' => '備考🐸',
            ],
            [
                'id' => 4,
                'type' => 0,
                'name' => '見積もり名',
                'user_id' => 4,
                'staff_name' => '担当者',
                'contact_id' => 13,
                'sub_total' => 220000,
                'total' => 242000,
                'payee' => "",
                'memo' => '備考🐸',
            ],
            [
                'id' => 5,
                'type' => 0,
                'name' => '見積もり名',
                'user_id' => 2,
                'staff_name' => '担当者',
                'contact_id' => 14,
                'sub_total' => 350000,
                'total' => 385000,
                'payee' => "",
                'memo' => '備考🐸',
            ],
            [
                'id' => 6,
                'type' => 0,
                'name' => '見積もり名',
                'user_id' => 5,
                'staff_name' => '担当者',
                'contact_id' => 15,
                'sub_total' => 150000,
                'total' => 175000,
                'payee' => "",
                'memo' => '備考🐸',
            ],
            [
                'id' => 7,
                'type' => 0,
                'name' => '見積もり名',
                'user_id' => 2,
                'staff_name' => '担当者',
                'contact_id' => 41,
                'sub_total' => 150000,
                'total' => 175000,
                'payee' => "",
                'memo' => '複数見積もりテスト備考',
            ],
            [
                'id' => 8,
                'type' => 0,
                'name' => '見積もり名',
                'user_id' => 2,
                'staff_name' => '担当者',
                'contact_id' => 41,
                'sub_total' => 180000,
                'total' => 198000,
                'payee' => "",
                'memo' => '複数見積もりテスト2備考',
            ],
            [
                'id' => 9,
                'type' => 0,
                'name' => '見積もり名',
                'user_id' => 2,
                'staff_name' => '担当者',
                'contact_id' => 39,
                'sub_total' => 350000,
                'total' => 385000,
                'payee' => "",
                'memo' => 'ContactTest::testResultCustomer()用',
            ],
            [
                'id' => 10,
                'type' => 0,
                'name' => '見積もり名',
                'user_id' => 1,
                'staff_name' => '担当者',
                'contact_id' => 59,
                'sub_total' => 350000,
                'total' => 385000,
                'payee' => "",
                'memo' => '本部見積もり用',
            ],
            [
                'id' => 11,
                'type' => 0,
                'name' => '見積もり名',
                'user_id' => 1,
                'staff_name' => '担当者',
                'contact_id' => 59,
                'sub_total' => 250000,
                'total' => 275000,
                'payee' => "",
                'memo' => '本部見積もり用',
            ],
            [
                'id' => 12,
                'type' => 0,
                'name' => '見積もり名',
                'user_id' => 1,
                'staff_name' => '担当者',
                'contact_id' => 59,
                'sub_total' => 270000,
                'total' => 29999900,
                'payee' => "",
                'memo' => '本部見積もり用',
            ],
            [
                'id' => 13,
                'type' => 0,
                'name' => '見積もり名',
                'user_id' => 1,
                'staff_name' => '担当者',
                'contact_id' => 59,
                'sub_total' => 450000,
                'total' => 505000,
                'payee' => "",
                'memo' => '本部見積もり用',
            ],
            [
                'id' => 14,
                'type' => 1,
                'name' => 'カエルマテリアル株式会社',
                'user_id' => 2,
                'staff_name' => '担当者',
                'contact_id' => 61,
                'sub_total' => 450000,
                'total' => 505000,
                'payee' => "",
                'memo' => '本部見積もり用',
            ],
            [
                'id' => 15,
                'type' => 0,
                'name' => 'カエルマテリアル株式会社',
                'user_id' => 2,
                'staff_name' => '担当者',
                'contact_id' => 127,
                'sub_total' => 450000,
                'total' => 505000,
                'payee' => "",
                'memo' => 'エスキューブ工法展開テスト',
            ],
            [
                'id' => 16,
                'type' => 0,
                'name' => 'カエルマテリアル株式会社',
                'user_id' => 1,
                'staff_name' => '担当者',
                'contact_id' => 142,
                'sub_total' => 450000,
                'total' => 505000,
                'payee' => "",
                'memo' => 'テスト',
            ],
            [
                'id' => 17,
                'type' => 0,
                'name' => 'カエルマテリアル株式会社',
                'user_id' => 1,
                'staff_name' => '担当者',
                'contact_id' => 141,
                'sub_total' => 450000,
                'total' => 505000,
                'payee' => "",
                'memo' => 'テスト',
            ],
            // PDF改行テスト用
            [
                'id' => 18,
                'type' => 1,
                'name' => 'PDF材料見積もりテスト株式会社',
                'user_id' => 1,
                'staff_name' => '担当者',
                'contact_id' => 144,
                'sub_total' => 450000,
                'total' => 505000,
                'payee' => "【納期に関して】通常（景観用人工芝のご注文）の場合、ご入金確認後7営業日程度での発送となります。\r\n【お支払い条件】前金にてご入金\r\n振込先】サンプル銀行 本店 普通 0000000 サンプル株式会社\r\n※振込手数料につきましてはお客様負担でお願いいたします",
                'memo' => "【納期に関して】通常（景観用人工芝のご注文）の場合、ご入金確認後7営業日程度での発送となります。\r\n【お支払い条件】前金にてご入金\r\n振込先】サンプル銀行 本店 普通 0000000 サンプル株式会社\r\n※振込手数料につきましてはお客様負担でお願いいたします"
            ],
            // PDF改行テスト用
            [
                'id' => 19,
                'type' => 0,
                'name' => 'PDF施工見積もりテスト株式会社',
                'user_id' => 1,
                'staff_name' => '担当者',
                'contact_id' => 144,
                'sub_total' => 450000,
                'total' => 505000,
                'payee' => "【納期に関して】通常（景観用人工芝のご注文）の場合、ご入金確認後7営業日程度での発送となります。\r\n【お支払い条件】前金にてご入金\r\n振込先】サンプル銀行 本店 普通 0000000 サンプル株式会社\r\n※振込手数料につきましてはお客様負担でお願いいたします",
                'memo' => "【納期に関して】通常（景観用人工芝のご注文）の場合、ご入金確認後7営業日程度での発送となります。\r\n【お支払い条件】前金にてご入金\r\n振込先】サンプル銀行 本店 普通 0000000 サンプル株式会社\r\n※振込手数料につきましてはお客様負担でお願いいたします"
            ],
            // 100m2以上表示テスト用
            [
                'id' => 20,
                'type' => 0,
                'name' => '施工見積もりテスト株式会社',
                'user_id' => 2,
                'staff_name' => '担当者',
                'contact_id' => 158,
                'sub_total' => 450000,
                'total' => 505000,
                'payee' => "【納期に関して】通常（景観用人工芝のご注文）の場合、ご入金確認後7営業日程度での発送となります。\r\n【お支払い条件】前金にてご入金\r\n振込先】サンプル銀行 本店 普通 0000000 サンプル株式会社\r\n※振込手数料につきましてはお客様負担でお願いいたします",
                'memo' => "【納期に関して】通常（景観用人工芝のご注文）の場合、ご入金確認後7営業日程度での発送となります。\r\n【お支払い条件】前金にてご入金\r\n振込先】サンプル銀行 本店 普通 0000000 サンプル株式会社\r\n※振込手数料につきましてはお客様負担でお願いいたします"
            ],
            // 材料見積もり100m2以上表示テスト用
            [
                'id' => 21,
                'type' => 1,
                'name' => '材料見積もりテスト株式会社',
                'user_id' => 2,
                'staff_name' => '担当者',
                'contact_id' => 159,
                'sub_total' => 450000,
                'total' => 505000,
                'payee' => "【納期に関して】通常（景観用人工芝のご注文）の場合、ご入金確認後7営業日程度での発送となります。\r\n【お支払い条件】前金にてご入金\r\n振込先】サンプル銀行 本店 普通 0000000 サンプル株式会社\r\n※振込手数料につきましてはお客様負担でお願いいたします",
                'memo' => "【納期に関して】通常（景観用人工芝のご注文）の場合、ご入金確認後7営業日程度での発送となります。\r\n【お支払い条件】前金にてご入金\r\n振込先】サンプル銀行 本店 普通 0000000 サンプル株式会社\r\n※振込手数料につきましてはお客様負担でお願いいたします"
            ],
        ]);
    }
}
