apiVersion: v1
kind: ServiceAccount
metadata:
  name: sales-app-sa
  namespace: sales-app
# Prevent tokens from being automatically mounted to Pods
# This restricts the blast radius if an attacker gets shell access
automountServiceAccountToken: false
