apiVersion: v1
kind: Service
metadata:
  name: sales-service
  namespace: sales-app
spec:
  # 【レクチャー: FargateとALBの連携】
  # Fargate上のPodには直接IPでトラフィックを流す(target-type: ip)ため、
  # NodePortではなくClusterIPで定義します。
  type: ClusterIP
  selector:
    app: sales
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
