apiVersion: v1
kind: Service
metadata:
  name: sales-service
  namespace: sales-app
spec:
  type: ClusterIP # Use ClusterIP; ingress controller (ALB) handles external access
  selector:
    app: sales
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
